apiVersion: openslo/v1
kind: SLO
metadata:
  name: slo.cart.availability
spec:
  service: cart
  indicator:
    metadata:
      name: sli.cart.success
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: Prometheus
            metricSourceRef: prometheus-datasource
            spec:
              query: |
                sum(increase(http_requests_total{service="cart",code=~"2..|3.."}[30d]))
        total:
          metricSource:
            type: Prometheus
            metricSourceRef: prometheus-datasource
            spec:
              query: |
                sum(increase(http_requests_total{service="cart"}[30d]))
  timeWindow:
    - duration: 30d
      isRolling: true
  budgetingMethod: Occurrences
  objectives:
    - target: 0.999
